apiVersion: v1
kind: ConfigMap
metadata:
  name: nginxconfigmap
  namespace: "default"
data:
  nginx.conf: |-
    user nginx;
    worker_processes  10;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       80;
          server_name  localhost;
          location / {
            root   /usr/share/nginx/html; #Change this line
            index  index.html index.htm;
        }
      }
    }