# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secret-provider
  namespace: api
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Set to true for using managed identity
    userAssignedIdentityID: efdbae8b-54a8-4ec2-a645-3becd2e4f7e2   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: cluster-vault-oh-team4        # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: SQLDBNAME
          objectAlias: SQL_DBNAME
          objectType: secret              # object types: secret, key, or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQLPASSWORD
          objectAlias: SQL_PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: SQLSERVER
          objectAlias: SQL_SERVER
          objectType: secret
          objectVersion: ""
        - |
          objectName: SQLUSER
          objectAlias: SQL_USER
          objectType: secret
          objectVersion: ""
    tenantId: b1e79fe8-a24f-417c-87e7-95e4a5932044