apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: tripviewer
          image: registrywnq0978.azurecr.io/tripviewer:1.0
          env:
            - name: USERPROFILE_API_ENDPOINT
              value: http://userprofile-service.api:6379
            - name: TRIPS_API_ENDPOINT
              value: http://trips-service.api:6379
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer-service
  namespace: web
spec:
  ports:
    - port: 6379
      targetPort: 80
  selector:
    app: tripviewer
