apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: trips
          image: registrywnq0978.azurecr.io/trips:1.0
          env:
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: sqlconfig
                  key: SQL_USER
                  optional: false
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqlconfig
                  key: SQL_PASSWORD
                  optional: false
            - name: SQL_SERVER
              valueFrom:
                secretKeyRef:
                  name: sqlconfig
                  key: SQL_SERVER
                  optional: false
            - name: SQL_DBNAME
              valueFrom:
                secretKeyRef:
                  name: sqlconfig
                  key: SQL_DBNAME
                  optional: false
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
---
apiVersion: v1
kind: Service
metadata:
  name: trips-service
  namespace: api
spec:
  ports:
    - port: 6379
      targetPort: 80
  selector:
    app: trips
