apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: trips
          image: registrywnq0978.azurecr.io/trips:1.0
          volumeMounts:
          - name: secret-provider
            mountPath: "/secrets"
            readOnly: true
      volumes:
      - name: secret-provider
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "secret-provider"
---
apiVersion: v1
kind: Service
metadata:
  name: trips-service
  namespace: api
spec:
  ports:
    - port: 6379
      targetPort: 80
  selector:
    app: trips
